### ISSUE TITLE
possibility to send SMS silently

### ISSUE THREAD

**Issue by silversquall** [fluttercommunity/flutter_sms#11]
The plugin opens the SMS app, it then requires another tap to send the sms.

I would like to have the possibility to send the sms silently from my flutter app without having it going to the background.

thx.

**Comment by AppleEducate** [comment]
There is no way to send silently on iOS and android just changed the guidelines and unless you are a phone or sms application you do not get this feature. That is outside the scope of this plugin.

**Comment by 926** [comment]
Mr Davis,
Thanks again for yet another great repo !
Does this restriction also apply if apk is not distributed on google play ?
Is sending sms in the background purely "forbidden" by android services ?
No bad intentions, it's for avoiding mistakes while sending financial sms in remote areas.

**Comment by rodydavis** [comment]
If I reference the api it breaks for everyone. So it’s outside of the scope of the plugin. But outside google play anything goes
