### ISSUE TITLE
Add posibility to read out all sms

### ISSUE THREAD

**Issue by akarabach** [fluttercommunity/flutter_sms#13]
It would be nice to be able to read sms for both Android and iOS

**Comment by DigitalSolomon** [comment]
As in, read all of the private SMS messages on the device?

**Comment by akarabach** [comment]
yup

**Comment by rodydavis** [comment]
Not possible on iOS and android will remove you app. This is outside the scope of this plugin. Feel free to submit a PR

**Comment by bawantha** [comment]
@rodydavis  What? Then how app like Truecaller stays. It can read SMS and send SMS (obviously with user's consent)

**Comment by rodydavis** [comment]
You are welcome to submit a PR to add the functionality and link to the apple documentation. 

But I have not found it and this plugin is focused on sending messages.

If the functionality exists then a new plugin could depend on this one to provide a full chat app api.
