### ISSUE TITLE
No implementation found for method sendSMS on channel flutter_sms

### ISSUE THREAD

**Issue by kashifg4171** [fluttercommunity/flutter_sms#18]

**Comment by rodydavis** [comment]
Please provide more info. Flutter doctor and details about the project and platform running.

**Comment by rodydavis** [comment]
Fixed on 2.0.0

**Comment by ChandraPrakashJangid** [comment]
I am getting same issue.

**Comment by rodydavis** [comment]
What platform?

**Comment by rodydavis** [comment]
Just tested on iOS and works fine.

**Comment by ChandraPrakashJangid** [comment]
@rodydavis I am getting this on Android.

**Comment by abhriyaroy** [comment]
Just got the same issue on iOS

**Comment by adarshbalu** [comment]
Same issue here using android.
The way of implementation shown on docs is 

`void _sendSMS(String message, List<String> recipents) async {
 String _result = await FlutterSms
        .sendSMS(message: message, recipients: recipents)
        .catchError((onError) {
      print(onError);
    });
print(_result);
}`

The **FlutterSms** shows an error , when I remove the FlutterSms the error is gone but the MissingPluginException is thrown.

**Comment by gersonfa** [comment]
I solved it running "flutter clean", "flutter build bundle".

**Comment by cybot-des** [comment]
was facing same issue while running on android.
just run "flutter clean" command and restart your app...it solved the issue

**Comment by rodydavis** [comment]
fixed on version `2.3.1` reopen if it is still an issue

**Comment by kanojia-gaurav** [comment]
same issue

**Comment by kanojia-gaurav** [comment]
> Same issue here using android.
> The way of implementation shown on docs is
> 
> `void _sendSMS(String message, List<String> recipents) async { String _result = await FlutterSms .sendSMS(message: message, recipients: recipents) .catchError((onError) { print(onError); }); print(_result); }`
> 
> The **FlutterSms** shows an error , when I remove the FlutterSms the error is gone but the MissingPluginException is thrown.

same issue bro

**Comment by tjcode19** [comment]
Has this issue been solved please?

**Comment by kanojia-gaurav** [comment]
> Has this issue been solved please?

Buddy use this instead of that

sms_maintained 0.2.5

use this package and it works same and easy to use.

**Comment by kanojia-gaurav** [comment]
> > > Has this issue been solved please?
> > 
> > 
> > Buddy use this instead of that
> > sms_maintained 0.2.5
> > use this package and it works same and easy to use.
> 
> Same problem on iOS, can you help me? Works fine on Android but not on my iPhone

Bro i haven't used for iphone . another way is hard coding of java and kotlin U can create project in kotlin and it will work fine i think so as kotlin code is also available on the stackoverflow (https://stackoverflow.com/questions/48309062/flutter-send-sms-with-device-automatically?noredirect=1&lq=1). It will work fine for kotlin but for java it is giving me the error.

**Comment by anuragsharma7** [comment]
Getting same issue

**Comment by wang305305** [comment]
Getting the same issue, it works on Android but not IOS.
