### ISSUE TITLE
Android build fails due to "import 'dart:html'"

### ISSUE THREAD

**Issue by PerLycke** [fluttercommunity/flutter_sms#23]
Building flutter_sms: ^2.0.1+2 for Android fails with the following message:

> Compiler message:                                                       
> ../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:3:8: Error: Not found: 'dart:html'
> import 'dart:html' as html;                                             
>        ^                    

**Flutter doctor:**

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-GB)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.6)
> [✓] Connected device (2 available)
> 
> • No issues found!

**Comment by knyghtryda** [comment]
I'm having the same issue.  2.0.0+2 is still working.

**Comment by colinlemmon** [comment]
Having the same issue with 2.0.1+2

**Comment by aminjoharinia** [comment]
Having the same issue, tested both 2.0.1 +2 and 2.0.0 +2

**Comment by PerLycke** [comment]
> Having the same issue, tested both 2.0.1 +2 and 2.0.0 +2

2.0.0+2 works. You need to point to that exact version without the ^ at the beginning

**Comment by Stathis90** [comment]
Having the same issue with 2.0.1+2

**Comment by ZigaZumer** [comment]
¸Having the same issue with ^2.0.0+2

**Comment by adamCPP** [comment]
I'm having this issue on flutter_sms: ^2.0.1+2

**Comment by rdev-software** [comment]
Same

**Comment by knyghtryda** [comment]
I created a [PR](https://github.com/fluttercommunity/flutter_sms/pull/25) for this issue. Until then its probably safe to use use the previous version until the maintainer updates it.

**Comment by fuzzy-memory** [comment]
I am facing the same issues with 2.0.1+2
2.0.0 seems to be working just fine though

**Comment by amar-belkhede** [comment]
it is not working for 2.0.0 and 2.0.0+2 as well

**Comment by amar-belkhede** [comment]
Compiler message:
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:90:27: Error: Getter not found: 'window'.
      final _agent = html.window.navigator.userAgent;
                          ^^^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:3:8: Error: Not found: 'dart:html'
import 'dart:html' as html;                                             
       ^
                                                                        
Compiler message:
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:3:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart:34:18: Error: 'HttpRequest' isn't a type.
  final _xhrs = <HttpRequest>{};
                 ^^^^^^^^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:90:27: Error: Getter not found: 'window'.
      final _agent = html.window.navigator.userAgent;
                          ^^^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart:58:34: Error: 'Blob' isn't a type.
      var blob = xhr.response as Blob ?? Blob([]);
                                 ^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart:46:15: Error: The method 'HttpRequest' isn't defined for the class 'BrowserClient'.
 - 'BrowserClient' is from 'package:http/src/browser_client.dart' ('../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HttpRequest'.
    var xhr = HttpRequest();
              ^^^^^^^^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart:58:42: Error: The method 'Blob' isn't defined for the class 'BrowserClient'.
 - 'BrowserClient' is from 'package:http/src/browser_client.dart' ('../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Blob'.
      var blob = xhr.response as Blob ?? Blob([]);
                                         ^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart:59:20: Error: The method 'FileReader' isn't defined for the class 'BrowserClient'.
 - 'BrowserClient' is from 'package:http/src/browser_client.dart' ('../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FileReader'.
      var reader = FileReader();
                   ^^^^^^^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/packages/flutter/lib/src/painting/_network_image_web.dart:88:12: Error: Method not found: 'webOnlyInstantiateImageCodecFromUrl'.
    return ui.webOnlyInstantiateImageCodecFromUrl(resolved, // ignore: undefined_function
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:                                                    
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:567:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:760:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_serve
r/frontend_server.dart:536:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:40:22)
#5      starter (package:flutter_frontend_server/server.dart:178:27)    
#6      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:8:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.                                                           

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Amar\flutter_windows_v1.12.13+hotfix.5-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882      

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Amar\flutter_windows_v1.12.13+hotfix.5-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        32.0s
Exception: Gradle task assembleDebug failed with exit code 1

Amar@DESKTOP-FCL9CDM MINGW64 ~/MyProjects/eyemagnett/f2f (master)
$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering
with "--enable-software-rendering".
Launching lib\main.dart on Android SDK built for x86 in debug mode...

Compiler message:
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:90:27: Error: Getter not found: 'window'.
      final _agent = html.window.navigator.userAgent;                   
                          ^^^^^^                                        
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:3:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
Invalid depfile: C:\Users\Amar\MyProjects\eyemagnett\f2f\.dart_tool\flutter_build\f8558b0eb6e113cd4f21a8321e06344d\kernel_snapshot.dInvalid depfile: C:\Users\Amar\MyProjects\eyemagnett\f2f\.dart_tool\flutter_build\f8558b0eb6e113cd4f21a8321e06344d\kernel_snapshot.d
Compiler message:
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:3:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart:34:18: Error: 'HttpRequest' isn't a type.
  final _xhrs = <HttpRequest>{};
                 ^^^^^^^^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:90:27: Error: Getter not found: 'window'.
      final _agent = html.window.navigator.userAgent;
                          ^^^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart:58:34: Error: 'Blob' isn't a type.
      var blob = xhr.response as Blob ?? Blob([]);
                                 ^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart:46:15: Error: The method 'HttpRequest' isn't defined for the class 'BrowserClient'.
 - 'BrowserClient' is from 'package:http/src/browser_client.dart' ('../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'HttpRequest'.
    var xhr = HttpRequest();
              ^^^^^^^^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart:58:42: Error: The method 'Blob' isn't defined for the class 'BrowserClient'.
 - 'BrowserClient' is from 'package:http/src/browser_client.dart' ('../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Blob'.
      var blob = xhr.response as Blob ?? Blob([]);
                                         ^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart:59:20: Error: The method 'FileReader' isn't defined for the class 'BrowserClient'.
 - 'BrowserClient' is from 'package:http/src/browser_client.dart' ('../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.1/lib/src/browser_client.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FileReader'.
      var reader = FileReader();
                   ^^^^^^^^^^
../../../flutter_windows_v1.12.13+hotfix.5-stable/flutter/packages/flutter/lib/src/painting/_network_image_web.dart:88:12: Error: Method not found: 'webOnlyInstantiateImageCodecFromUrl'.
    return ui.webOnlyInstantiateImageCodecFromUrl(resolved, // ignore: undefined_function
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dar
tlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:567:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:760:21)
<asynchronous suspension>
#3      FrontendCompiler.compile 
(package:frontend_server/frontend_server.dart:536:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:40:22)
#5      starter (package:flutter_frontend_server/server.dart:1
78:27)
#6      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:8:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.
                                                                        
FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Amar\flutter_windows_v1.12.13+hotfix.5-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882      

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Amar\flutter_windows_v1.12.13+hotfix.5-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        20.7s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by talcott** [comment]
For me worked using version 2.0.0. Thanks a lot Per Lycke

**Comment by sonia1997** [comment]
Thanks Per Lycke! It works.

**Comment by ankittale** [comment]
@talcott and @sonia1997 Did it work on iOS it giving me error while build generation.

**Comment by softmarshmallow** [comment]
what cuases this?

**Comment by rodydavis** [comment]
fixed on version `2.3.1` reopen if it is still an issue
