### ISSUE TITLE
Compiler message: ../../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter _sms_platform.dart:3:8: Error: Not found: 'dart:html' import 'dart:html' as html; However this https://github.com/fluttercommunity/flutter_sms/pull/25 worked for me!

### ISSUE THREAD

**Issue by simsolTech** [fluttercommunity/flutter_sms#26]
Getting the above error. https://github.com/fluttercommunity/flutter_sms/pull/25 Worked for me!

**Comment by Yann39** [comment]
Same here

**Comment by bsutton** [comment]
I'm also having this issue.

**Comment by CripyIce** [comment]
Also facing this issue.

**Comment by shachneff** [comment]
+1

**Comment by adarshbalu** [comment]
Same here.

**Comment by adarshbalu** [comment]
> Same here, workouround is to downgrade to `flutter_sms: 2.0.0+2` while maintainer fix this.

Not Working.

**Comment by simsolTech** [comment]
https://github.com/fluttercommunity/flutter_sms/pull/25 - This works for me!

**Comment by bawantha** [comment]
same

**Comment by bawantha** [comment]
I don't about terminal teicks bt completely deleting v 2.0.1 and pubspec.lock after  downgrade to 2.0.0 worked for me

**Comment by dheerajy2310** [comment]
> > same,any updates on this issue ?
> 
> downgrade to v2.0.0

it helped me!
Thanks a lot!

**Comment by rodydavis** [comment]
fixed on version `2.3.1` reopen if it is still an issue
