### ISSUE TITLE
Android always says "SMS Sent!"

### ISSUE THREAD

**Issue by lauralarez** [fluttercommunity/flutter_sms#27]
On iOS when I try to send a message I receive as a result either "sent" or "cancelled" but when on Android I always get "SMS Sent!" no matter what I do.

**Comment by davidbrenner** [comment]
I'm also experiencing this. It's particularly frustrating as I was hoping to send a series of SMS messages based on the user's selection of people from their contacts, which would require blocking on success/cancelled for each message.

The code to detect and set result on Android is commented out. See: https://github.com/fluttercommunity/flutter_sms/blob/9a874fc3d23657d7383bb0725d23f4d965820c03/android/src/main/kotlin/com/example/flutter_sms/FlutterSmsPlugin.kt#L76-L84

**Comment by rodydavis** [comment]
fixed on version `2.3.1` reopen if it is still an issue

**Comment by Ibtesam-Mahmood** [comment]
I can confirm that this issue persists in `2.3.3`. It also seems like I am not able to actually pass the message into the dialog. Please let me know if there is a solution.
