### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by bsutton** [fluttercommunity/flutter_sms#28]
Gentlefolk.
Can I ask for some documentation improvements.

1) what is the difference between sendSMS and launchSMS?
2) what actions are required to support dual sim cards.
3) the values return by sendSMS and launchSMS

**Comment by rodydavis** [comment]
1. There should be a doc comment that explains it for each method
2. No support at this time but PRs are welcome
3. General log messages

**Comment by rodydavis** [comment]
sendSMS is for using the url scheme, and launchSMS is for opening the native dialog
