### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by mengsiyitiaojie** [fluttercommunity/flutter_sms#30]
Compiler message:
../lib/src/flutter_sms_platform.dart:3:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
../lib/src/flutter_sms_platform.dart:90:27: Error: Getter not found: 'window'.
      final _agent = html.window.navigator.userAgent;
                          ^^^^^^

Compiler message:
../lib/src/flutter_sms_platform.dart:3:8: Error: Not found: 'dart:html'
import 'dart:html' as html;

**Comment by knyghtryda** [comment]
see #23 for reason why.  Short answer, either use 2.0.0+2 or merge in PR #25 to your own fork.

**Comment by rodydavis** [comment]
fixed on version `2.3.1` reopen if it is still an issue
