### ISSUE TITLE
Is this default SMS app opener

### ISSUE THREAD

**Issue by bawantha** [fluttercommunity/flutter_sms#31]
Last 2 screenshot of documentation  confuse me. Why there are default SMS app's of android and iOS .Can this package send SMS without interaction of those apps

**Comment by shinewanna** [comment]
No, u can't with this package, 
if u want to send without user interaction, you can send with this package or other.
[https://pub.dev/packages/background_sms](url)

**Comment by bawantha** [comment]
Thank you
