### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by guilhermecarvalhocarneiro** [fluttercommunity/flutter_sms#32]
I'm trying to use the package, but after configuring and importing the package when I try to run the app the message appears:

/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:3:8: Error: Not found: 'dart: html'
import 'dart: html' as html;

**Comment by P-B1101** [comment]
same here :|

**Comment by P-B1101** [comment]
downgrade to 1.1.0 for now.

**Comment by mtgperales** [comment]
Still experiencing it

> ../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:3:8: Error: Not found: 'dart:html'
import 'dart:html' as html;                                             
       ../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_sms-2.0.1+2/lib/src/flutter_sms_platform.dart:90:27: Error: Getter not found: 'window'.
      final _agent = html.window.navigator.userAgent;                   
                       
Any solution aside from downgrading?

**Comment by rodydavis** [comment]
fixed on version `2.3.1` reopen if it is still an issue
