### ISSUE TITLE
[Dependancies] plugin_platform_interface 2.0.0

### ISSUE THREAD

**Issue by tlkops** [fluttercommunity/flutter_sms#37]
Hello,

Currently flutter_sms depends on plugin_platform_interface 1.0.1, but as firebase_messaging >=9.0.0  depends on firebase_messaging_platform_interface ^2.0.0, it makes them unusable together.
Would that take a lot of work to bump this dependancy version to 2.0.0?

**Comment by rodydavis** [comment]
fixed on version `2.3.1`
