### ISSUE TITLE
Just a question or feature request

### ISSUE THREAD

**Issue by jordantsap** [fluttercommunity/flutter_sms#39]
I use other package to send sms without opening sms manager to android.
I use the package to open sms dialog inios and send predefined phone number and sms message:
`void _sendSMS(String message, String number) async {
      bool _result = await launchSms(message: message, number: number)
          .catchError((onError) {
        print(onError);
      });
      print(_result);
    }
    String message = "Sender has a car issue.\n"
        "Date-time at ${DateTime.now()}\n"
        "Location:\n"
        "$mapLink";
    String number = bookerPhone;`
It works as expected, but
is there a way to return to the app after the user sends the sms?

**Comment by rodydavis** [comment]
Currently not possible, but im open for PRs!
