### ISSUE TITLE
The plugins flutter_sms use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by shelarvs** [fluttercommunity/flutter_sms#51]
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

Request you please resolve the issue ASAP

**Comment by rizwan3d** [comment]
+1

**Comment by Temur87** [comment]
+1

**Comment by SilkyPantsDan** [comment]
Looks to be merged now?

https://github.com/fluttercommunity/flutter_sms/pull/49
